<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3GWTKhz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3GWTKhz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3GWTKhz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3GWTKhz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3GWTKhz\App_KernelDevDebugContainer([
    'container.build_hash' => '3GWTKhz',
    'container.build_id' => '13155798',
    'container.build_time' => 1623230868,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3GWTKhz');
